name: Deploy Application
on: 
  push: 
    branches: 
      - main
jobs:
  deploy:
    uses: sridhar7601/infrastructure-repo/.github/workflows/terraform-s3.yml@main
    with:
      environment: production
      app_name: my-app
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
