name: Deploy Application
on: 
  push: 
    branches: 
      - main
jobs:
  deploy:
    uses: sridhar7601/infrastructure-repo/.github/workflows/terraform-docker.yml@main
    with:
      environment: production
      enable_docker: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
